# Site settings
title: inbrief
email: getinbrief@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Everything's in brief
baseurl: "/app-data" # the subpath of your site, e.g. /blog/
url: "http://www.getinbrief.xyz" # the base hostname & protocol for your site
twitter_username: getinbrief
github_username:  getinbrief
paginate: 3

# Build settings
markdown: kramdown
